<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['code' => 'KNCR001', 'name' => 'Domba Medium KNCR001', 'category' => 'Medium', 'price' => 3960000, 'weight' => 33.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR002', 'name' => 'Domba Ekonomis KNCR002', 'category' => 'Ekonomis', 'price' => 3480000, 'weight' => 29.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR003', 'name' => 'Domba Ekonomis KNCR003', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR004', 'name' => 'Domba Ekonomis KNCR004', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR005', 'name' => 'Domba Ekonomis KNCR005', 'category' => 'Ekonomis', 'price' => 3000000, 'weight' => 25.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR006', 'name' => 'Domba Ekonomis KNCR006', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR007', 'name' => 'Domba Ekonomis KNCR007', 'category' => 'Ekonomis', 'price' => 3240000, 'weight' => 27.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR008', 'name' => 'Domba Ekonomis KNCR008', 'category' => 'Ekonomis', 'price' => 2760000, 'weight' => 23.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR009', 'name' => 'Domba Ekonomis KNCR009', 'category' => 'Ekonomis', 'price' => 3240000, 'weight' => 27.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR010', 'name' => 'Domba Ekonomis KNCR010', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR011', 'name' => 'Domba Ekonomis KNCR011', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR012', 'name' => 'Domba Ekonomis KNCR012', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR013', 'name' => 'Domba Ekonomis KNCR013', 'category' => 'Ekonomis', 'price' => 3000000, 'weight' => 25.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR014', 'name' => 'Domba Ekonomis KNCR014', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR015', 'name' => 'Domba Ekonomis KNCR015', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR016', 'name' => 'Domba Medium KNCR016', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR017', 'name' => 'Domba Medium KNCR017', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR018', 'name' => 'Domba Ekonomis KNCR018', 'category' => 'Ekonomis', 'price' => 2760000, 'weight' => 23.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR019', 'name' => 'Domba Ekonomis KNCR019', 'category' => 'Ekonomis', 'price' => 3240000, 'weight' => 27.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR020', 'name' => 'Domba Ekonomis KNCR020', 'category' => 'Ekonomis', 'price' => 3480000, 'weight' => 29.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR021', 'name' => 'Domba Ekonomis KNCR021', 'category' => 'Ekonomis', 'price' => 2880000, 'weight' => 24.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR022', 'name' => 'Domba Ekonomis KNCR022', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR023', 'name' => 'Domba Ekonomis KNCR023', 'category' => 'Ekonomis', 'price' => 3240000, 'weight' => 27.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR024', 'name' => 'Domba Ekonomis KNCR024', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR025', 'name' => 'Domba Ekonomis KNCR025', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR026', 'name' => 'Domba Ekonomis KNCR026', 'category' => 'Ekonomis', 'price' => 2520000, 'weight' => 21.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR027', 'name' => 'Domba Ekonomis KNCR027', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR028', 'name' => 'Domba Ekonomis KNCR028', 'category' => 'Ekonomis', 'price' => 3000000, 'weight' => 25.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR029', 'name' => 'Domba Ekonomis KNCR029', 'category' => 'Ekonomis', 'price' => 3480000, 'weight' => 29.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR030', 'name' => 'Domba Ekonomis KNCR030', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR031', 'name' => 'Domba Ekonomis KNCR031', 'category' => 'Ekonomis', 'price' => 2880000, 'weight' => 24.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR032', 'name' => 'Domba Ekonomis KNCR032', 'category' => 'Ekonomis', 'price' => 3000000, 'weight' => 25.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR033', 'name' => 'Domba Ekonomis KNCR033', 'category' => 'Ekonomis', 'price' => 3240000, 'weight' => 27.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR034', 'name' => 'Domba Medium KNCR034', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR035', 'name' => 'Domba Ekonomis KNCR035', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR036', 'name' => 'Domba Ekonomis KNCR036', 'category' => 'Ekonomis', 'price' => 3480000, 'weight' => 29.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR037', 'name' => 'Domba Medium KNCR037', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR038', 'name' => 'Domba Ekonomis KNCR038', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR039', 'name' => 'Domba Medium KNCR039', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR040', 'name' => 'Domba Ekonomis KNCR040', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR041', 'name' => 'Domba Ekonomis KNCR041', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR042', 'name' => 'Domba Ekonomis KNCR042', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR043', 'name' => 'Domba Medium KNCR043', 'category' => 'Medium', 'price' => 4080000, 'weight' => 34.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR044', 'name' => 'Domba Ekonomis KNCR044', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR045', 'name' => 'Domba Medium KNCR045', 'category' => 'Medium', 'price' => 3840000, 'weight' => 32.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR046', 'name' => 'Domba Ekonomis KNCR046', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR047', 'name' => 'Domba Medium KNCR047', 'category' => 'Medium', 'price' => 3960000, 'weight' => 33.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR048', 'name' => 'Domba Medium KNCR048', 'category' => 'Medium', 'price' => 3840000, 'weight' => 32.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR049', 'name' => 'Domba Medium KNCR049', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR050', 'name' => 'Domba Medium KNCR050', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR051', 'name' => 'Domba Ekonomis KNCR051', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR052', 'name' => 'Domba Medium KNCR052', 'category' => 'Medium', 'price' => 3960000, 'weight' => 33.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR053', 'name' => 'Domba Ekonomis KNCR053', 'category' => 'Ekonomis', 'price' => 4200000, 'weight' => 35.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR054', 'name' => 'Domba Ekonomis KNCR054', 'category' => 'Ekonomis', 'price' => 3480000, 'weight' => 29.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR055', 'name' => 'Domba Ekonomis KNCR055', 'category' => 'Ekonomis', 'price' => 4200000, 'weight' => 35.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR056', 'name' => 'Domba Ekonomis KNCR056', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR057', 'name' => 'Domba Medium KNCR057', 'category' => 'Medium', 'price' => 3840000, 'weight' => 32.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR058', 'name' => 'Domba Ekonomis KNCR058', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR059', 'name' => 'Domba Medium KNCR059', 'category' => 'Medium', 'price' => 4080000, 'weight' => 34.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR060', 'name' => 'Domba Medium KNCR060', 'category' => 'Medium', 'price' => 3960000, 'weight' => 33.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR061', 'name' => 'Domba Ekonomis KNCR061', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR062', 'name' => 'Domba Ekonomis KNCR062', 'category' => 'Ekonomis', 'price' => 3360000, 'weight' => 28.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR063', 'name' => 'Domba Ekonomis KNCR063', 'category' => 'Ekonomis', 'price' => 4200000, 'weight' => 35.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR064', 'name' => 'Domba Medium KNCR064', 'category' => 'Medium', 'price' => 3960000, 'weight' => 33.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR065', 'name' => 'Domba Ekonomis KNCR065', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR066', 'name' => 'Domba Ekonomis KNCR066', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR067', 'name' => 'Domba Premium KNCR067', 'category' => 'Premium', 'price' => 4440000, 'weight' => 37.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR068', 'name' => 'Domba Ekonomis KNCR068', 'category' => 'Ekonomis', 'price' => 4200000, 'weight' => 35.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR069', 'name' => 'Domba Ekonomis KNCR069', 'category' => 'Ekonomis', 'price' => 3480000, 'weight' => 29.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR070', 'name' => 'Domba Ekonomis KNCR070', 'category' => 'Ekonomis', 'price' => 4200000, 'weight' => 35.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR071', 'name' => 'Domba Medium KNCR071', 'category' => 'Medium', 'price' => 4080000, 'weight' => 34.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR072', 'name' => 'Domba Ekonomis KNCR072', 'category' => 'Ekonomis', 'price' => 3480000, 'weight' => 29.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR073', 'name' => 'Domba Medium KNCR073', 'category' => 'Medium', 'price' => 3960000, 'weight' => 33.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR074', 'name' => 'Domba Medium KNCR074', 'category' => 'Medium', 'price' => 3840000, 'weight' => 32.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR075', 'name' => 'Domba Ekonomis KNCR075', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR076', 'name' => 'Domba Ekonomis KNCR076', 'category' => 'Ekonomis', 'price' => 4200000, 'weight' => 35.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR077', 'name' => 'Domba Ekonomis KNCR077', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR078', 'name' => 'Domba Ekonomis KNCR078', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR079', 'name' => 'Domba Ekonomis KNCR079', 'category' => 'Ekonomis', 'price' => 3120000, 'weight' => 26.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR080', 'name' => 'Domba Medium KNCR080', 'category' => 'Medium', 'price' => 3720000, 'weight' => 31.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR081', 'name' => 'Domba Medium KNCR081', 'category' => 'Medium', 'price' => 3840000, 'weight' => 32.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR082', 'name' => 'Domba Ekonomis KNCR082', 'category' => 'Ekonomis', 'price' => 3000000, 'weight' => 25.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR083', 'name' => 'Domba Ekonomis KNCR083', 'category' => 'Ekonomis', 'price' => 4200000, 'weight' => 35.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR084', 'name' => 'Domba Medium KNCR084', 'category' => 'Medium', 'price' => 4080000, 'weight' => 34.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR085', 'name' => 'Domba Ekonomis KNCR085', 'category' => 'Ekonomis', 'price' => 3600000, 'weight' => 30.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR086', 'name' => 'Domba Premium KNCR086', 'category' => 'Premium', 'price' => 4800000, 'weight' => 40.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR087', 'name' => 'Domba Premium KNCR087', 'category' => 'Premium', 'price' => 5040000, 'weight' => 42.0, 'stock' => 1, 'is_active' => true],
            ['code' => 'KNCR088', 'name' => 'Domba Premium KNCR088', 'category' => 'Premium', 'price' => 5520000, 'weight' => 46.0, 'stock' => 1, 'is_active' => true],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}